/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import { sendContactEmail } from "@/lib/api/email";
import { MapPin, Phone, Accessibility, Coffee, Calendar, CreditCard } from "lucide-react";

type ContactSplitEmailProps = {
  tag: string;
  title: string;
  description: string;
  inputPlaceholder: string;
  buttonText: string;
  onSubmit?: (email: string) => void;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const ContactInline = () => {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      await sendContactEmail({ email });
      undefined?.(email);
      setEmail("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to send. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up" className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <div className="flex items-center justify-center py-15 md:py-20 card rounded">
            <div className="flex flex-col items-center w-full gap-2 px-5">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Get In Touch"}</p>
              </div>

              <TextAnimation
                text={"Schedule Your Sylmar Family Dental Practice Experience"}
                variant={"slide-up"}
                gradientText={true}
                tag="h2"
                className="text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
              />

              <TextAnimation
                text={"Connect with our team to discuss your smile goals and discover how our personalized treatments can transform your dental health and confidence."}
                variant={"slide-up"}
                gradientText={false}
                tag="p"
                className="md:max-w-8/10 text-lg md:text-xl leading-snug text-center text-balance"
              />

              <form
                onSubmit={handleSubmit}
                className="flex flex-col md:flex-row w-full md:w-8/10 2xl:w-6/10 gap-3 md:gap-1 p-1 mt-2 md:mt-3 card rounded"
              >
                <input
                  type="email"
                  placeholder={"Enter your email"}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="flex-1 px-5 py-3 md:py-0 text-base text-center md:text-left bg-transparent placeholder:opacity-75 focus:outline-none truncate"
                  aria-label="Email address"
                />
                <button
                  type="submit"
                  disabled={isLoading}
                  className="flex items-center justify-center h-10 px-6 text-sm rounded primary-button text-primary-cta-text cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isLoading ? "Sending..." : "Get Started"}
                </button>
              </form>

              {error && (
                <p className="text-sm text-red-500 text-center">{error}</p>
              )}
            </div>
          </div>

          <div className="card rounded p-8 flex flex-col gap-6 h-full justify-center">
            <h3 className="text-2xl font-semibold text-foreground">Practice Details</h3>
            
            <div className="flex flex-col gap-4">
              <div className="flex items-start gap-3">
                <MapPin className="w-5 h-5 text-primary-cta shrink-0 mt-1" />
                <div>
                  <p className="font-medium text-foreground">Address</p>
                  <p className="text-accent">13424 Telecom Dr SECOND FLOOR<br/>Temple Terrace, FL 33637, United States</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Phone className="w-5 h-5 text-primary-cta shrink-0 mt-1" />
                <div>
                  <p className="font-medium text-foreground">Phone</p>
                  <p className="text-accent">+1 813-898-2523</p>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mt-2">
                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-foreground font-medium">
                    <Accessibility className="w-4 h-4 text-primary-cta" />
                    <h4>Accessibility</h4>
                  </div>
                  <ul className="text-sm text-accent space-y-1 pl-6">
                    <li>• Wheelchair-accessible car park</li>
                    <li>• Wheelchair-accessible entrance</li>
                    <li>• Wheelchair-accessible toilet</li>
                  </ul>
                </div>

                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-foreground font-medium">
                    <Coffee className="w-4 h-4 text-primary-cta" />
                    <h4>Amenities</h4>
                  </div>
                  <ul className="text-sm text-accent space-y-1 pl-6">
                    <li>• Restroom</li>
                  </ul>
                </div>

                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-foreground font-medium">
                    <Calendar className="w-4 h-4 text-primary-cta" />
                    <h4>Planning</h4>
                  </div>
                  <ul className="text-sm text-accent space-y-1 pl-6">
                    <li>• Appointment required</li>
                    <li>• Appointments recommended</li>
                  </ul>
                </div>

                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-foreground font-medium">
                    <CreditCard className="w-4 h-4 text-primary-cta" />
                    <h4>Payments</h4>
                  </div>
                  <ul className="text-sm text-accent space-y-1 pl-6">
                    <li>• Credit cards</li>
                    <li>• Debit cards</li>
                    <li>• NFC mobile payments</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
