// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitKpi from "@/components/sections/hero/HeroSplitKpi";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroSplitKpi
        textAnimation="slide-up"
        tag="Sylmar Family Dental Practice"
        title="Sylmar Family Dental Practice"
        description="Experience world-class cosmetic and restorative dentistry with cutting-edge technology and personalized care in Temple Terrace, Florida."
        primaryButton={{ text: "View Our Services", href: "#services" }}
        secondaryButton={{ text: "Book Your Visit", href: "#contact" }}
        imageSrc="https://storage.googleapis.com/webild/default/templates/dentist/hero/hero1.avif"
        kpis={[{"label":"Google Rating","value":"4.7"},{"label":"Patient Reviews","value":"23+"},{"label":"Opens At","value":"8:30 AM"}]}
      />
            </div>
  );
}
